import PageHead from '../components/PageHead';

export default function Terms() {
    return (
        <div>
            <PageHead
                title="terms & conditions | Finisia"
                description="Finance made simple, smooth and affordable. Finisia deals with all things regarding your personal finance requirement, so that you don’t have to."
            />
            <section className="sc-mp0306-0 hCldjG">
                <div className="sc-mp0306-1 hBqLhy">Terms & Condition</div>
                <div className="sc-mp0306-5 bFeeNf">
                    <div>
                        <p>Last updated on 19 April 2022</p>
                        <p></p>
                        <p>We at the CRED group i.e. Dreamplug Technologies Private Limited and its subsidiaries, (“the Company/Dreamplug/We/Us/CRED”) are committed to protecting the privacy and security of your personal information. Your privacy is important to us and maintaining your trust is paramount.</p>
                        <p>This Privacy Policy explains how we collect, use, process and disclose information about you. By using our website/app and affiliated services, you consent to the terms of our privacy policy (“<strong>Privacy Policy</strong>”) in addition to our Terms of Use. We encourage you to read this Privacy Policy regarding the collection, use, and disclosure of your information from time to time to keep yourself updated with the changes &amp; updated that we make to this Policy.</p>
                        <p>This Privacy Policy describes our privacy practices for all websites, products and services that are linked to it. However this policy does not apply to those affiliates and partners that have their own privacy policy. In such situations, we recommend that you read the privacy policy on the applicable site. Any capitalised terms not defined hereunder shall hold the same definition as provided under the Terms of Use.</p>
                        <h2><strong>1. Information we collect</strong></h2>
                        <p>The following information is collected by or on behalf of CRED.</p>
                        <h3><strong>1.1 Information You provide us</strong></h3>
                        <p>When you start using the CRED App, we ask you to provide certain information as part of the registration process, and in the course of your interface with the CRED App. We will collect this information through various means and in various places through the CRED App, including account registration forms, contact us forms, or when you otherwise interact with CRED including at customer support.</p>
                        <p>At the time of registration, we ask for the following personal information. Name (First Name, Last Name); Mobile Number; Email ID; Date of Birth; PAN Card.</p>
                        <p>Pursuant to the services consumed by You from time to time, we may explicitly seek additional information including address, payment or banking information, credit score, credit/debit card details and any other governmental identification numbers or documents. You may choose to provide such information if you wish to use the services provided by the App.</p>
                        <p>We will also maintain a record of the information you provide to us when using customer support services.</p>
                        <p>From time to time, during your use of the CRED App, CRED may require access to certain additional information such as SMS and contact details. Prior to accessing any such additional information, explicit consent shall be sought from you. Please note that even after consent has been provided by you, we only read transactional or promotional SMS and do not open, access or read any personal SMS.</p>
                        <p>Certain features may be restricted, unavailable or unusable if you choose not to provide certain information. For example: You would not be able to complete e-commerce transactions involving delivery if you choose to not share a delivery address. CRED may require you to provide PAN details before claiming certain rewards.</p>
                        <h3><strong>1.2 Information created when You use the CRED App</strong></h3>
                        <p>We collect information relating to your use of our website/app through the use of various technologies. This includes transaction details related to your use of our services including the type of services you requested, the payment method, amount and other related transactional and financial information. Further, depending on the rewards claimed by you or e-commerce orders placed by you, we may also collect the order details, delivery information etc. Further, when you visit our website/app, we may log certain information such as your IP address, browser type, mobile operating system, manufacturer and model of your mobile device, geolocation, preferred language, access time, and time spent. We will also collect information about the pages you view within our sites and other actions you take while visiting our website/app.</p>
                        <p>We also maintain some records of users who contact us for support, for the purpose of responding to such queries and other related activities. However, we do not provide this information to any third party without your permission, or utilize the same for any purposes not set out hereunder.</p>
                        <h3><strong>1.3 Information We Collect from Third Parties</strong></h3>
                        <p>We may, on your consent, request certain third parties to provide information about you to further personalize your experience on our website/app, and provide certain services that cannot be accessed by all users of the website/app.</p>
                        <p>CRED is currently open only to credit card holders, who have a credit score greater than or equal to 750, independently determined by third party service providers that are expressly authorised by you to process such information and distribute the same. For example, CRIF and Experian which are credit information companies registered under the Credit Information Companies (Regulation) Act, 2005 are among our partners. In order to check if you meet the above eligibility, you will be requested to provide us with explicit consent to procure the credit information, from our partners, at the time of registration. </p>
                        <p>In order to access CRED Mint and CRED Cash services, you will be required to complete KYC processes which may involve CRED along with its partners, fetching your KYC data from one or more KYC registries.</p>
                        <p>If you choose to link and connect your email account with CRED, we may access the said account for purposes including collecting your credit card bill details such as total amount due, minimum amount due and due date, and such other financial and transactional information to be able to do the following:</p>
                        <p>1.&nbsp;Manage all your credit card information at one place including reminding you of the payment due before the due date;</p>
                        <p>2. Curate offers and rewards customised for you;</p>
                        <p>3. Provide an insight into your spending pattern(s) to ensure you are aware of your spending and can make wiser decisions basis the same; </p>
                        <p>4.&nbsp;Identify utility billers and insurers / insurance service providers you transact with to fetch your utility bill and/or insurance details; and</p>
                        <p>5. Curate specific financial/investment/other products for you based on your financial transactions, investments, and past financial behaviour.</p>
                        <p>CRED’s access to the email account(s) is authorized through the email provider’s access mechanism. If you permit the CRED website/app to track your credit card accounts, the CRED website/app will securely store account details for each of your email accounts, including your sign-in user name and authorisation tokens for tracked accounts.</p>
                        <p><strong>You can choose to enable us to access one or more of your email accounts by explicitly consenting to each single account separately. Please note that your consent to any of the above is purely voluntary. You can de-link the access to your email any time you wish.</strong></p>
                        <p>We only read emails related to financial services such as credit card statements, loan statements, insurance policies, biller details etc and do not open, read or access any personal e-mails. For the sake of clarity, CRED employs automated processes for accessing and analysing information provided by you; where we may need to use our algorithm to access a password-protected document utilizing information provided by you. For further information on how we process email and the security protocol we follow click&nbsp;.</p>
                        <p>We may receive additional information about you, such as information to help detect fraud and safety issues, from third party service providers and/or partners, and combine it with information we have about you. We may receive information about you and your activities through partnerships, or about your experiences and interactions from our partner ad networks.</p>
                        <h2><strong>2. How We Use the Information we collect</strong></h2>
                        <p>We may use, store and process the information provided by you to (1) improve the services offered through the CRED App, (2) create and maintain a trusted and safe environment on CRED (such as complying with our legal obligations and compliance with our policies) and (3) provide, personalise, measure and improve our products and services.</p>
                        <p>The information collected through different channels, allows us to collect statistics about our website/app usage and effectiveness, personalise your experience whilst you are on our website/app,as well as customize our interactions with you and to enhance the scope of the App Services. The following paragraphs describe in more detail how we use your personal information.</p>
                        <h3><strong>2.1 Providing, understanding and improving service offered through the CRED App</strong></h3>
                        <p>Any information provided by you will be used for creating and updating your account and processing your transaction(s) or for any other purposes for which you have granted access to such information to us, based on your interaction with the CRED App.</p>
                        <p>To complete a financial transaction, we may share financial information (such as credit card details or other payment mode details) provided by you with authorised third-parties, for instance, our business partners, financial teams/institutions, or postal/ government authorities involved in fulfilment of the said transactions, if any. This does not include any information collected from e-mails. In connection with a financial transaction, we may also contact you as part of our customer satisfaction surveys or for market research purposes.</p>
                        <p>We may use the information collected to perform internal operations necessary to provide our services, including to troubleshoot software bugs and operational problems, to conduct data analysis, testing and research and to monitor and analyse usage and activity trends. We process this personal information for these purposes given our legitimate interest in improving the App Services.</p>
                        <p>In order to expand the scope of our services, we may from time to time, seek additional information from you.&nbsp;<strong>Any such collection of additional information and documents shall be subject to an explicit &amp; purpose specific consent sought from all Users.</strong></p>
                        <p>CRED will securely store account details for each of your credit card accounts, including your sign-in user name and authorisation tokens for tracked accounts. This information will be used to enable the CRED website/app to automatically access your applicable credit card statements to analyze, extract, and store information securely from such accounts for use on the CRED app or website.</p>
                        <h3><strong>2.2 Safety, security and resolution of issues</strong></h3>
                        <p>We may use your personal information, created as part of payment services availed by you, to ensure that your access and use of payment services is in compliance with our legal obligations (such as anti-money laundering regulations). We may share such information, with our advisors, third party service partners and providers for a seamless experience for you.</p>
                        <p>We may use the information to create and maintain a safe environment and use the same to detect and prevent fraud, span, abuse, security incidents and other harmful activity.</p>
                        <p>We use the information we collect (including recordings of customer support calls) to assist you when you contact our customer support services to investigate and resolve your queries, monitor and improve our customer support responses. Certain online transactions may involve us calling you. This may also involve online chats. Please be aware that it is our general practice to monitor and in some cases record such interactions for staff training or quality assurance purposes or to retain evidence of a particular transaction or interaction.</p>
                        <p>We intend to protect your personal information and to maintain its accuracy as confirmed by you. We implement reasonable physical, administrative, and technical safeguards to help us protect your personal information from unauthorised access, use, and disclosure. For example, we encrypt all sensitive personal information such as credit card information when we transmit such information over the internet. We also require that our commercial partners and vendors protect such information from unauthorised access, use, and disclosure.</p>
                        <p>We blend security at multiple steps within our products with state of the art technology to ensure our systems maintain strong security measures. The overall data and privacy security design allows us defend our systems ranging from low hanging issue up to sophisticated attacks. You can read more about it&nbsp; .</p>
                        <p>We are committed to protecting your data as if it were our own. You can find more details&nbsp;&nbsp;with detailed steps required to reproduce the vulnerability. We shall put best of our efforts to investigate and fix the legitimate issues in a reasonable time frame, meanwhile, requesting you not to publicly disclose it.</p>
                        <h3><strong>2.3 Sharing and Disclosure of data with Third Parties</strong></h3>
                        <p>As required by law, at times we might be required to disclose your personal information including personal, transactional and financial information to relevant regulatory, and governmental authorities and also to our advisors such as law firms and audit firms while responding to request from the regulatory authorities. In some cases, when we believe that such disclosure is necessary to protect our rights, or the rights of others, or to comply with a judicial proceeding, court order, or legal process served on our website/app we would share such information pursuant to a lawful request from law enforcement agencies.</p>
                        <p>Several CRED products, including but not limited to CRED Cash, CRED Mint and insurance policies or covers offered through the CRED App are offered in partnership with other commercial partners of CRED. While availing such products any data shared by you as well as the data collected from your use of the App shall be shared with the relevant third parties with whom CRED has partnered. Their use of this data shall be subject to their terms and conditions and privacy policy which may include sharing of this data with their sub-contractors.</p>
                        <p>Subject to explicit and prior consent from a you, we may use information created by your use of our App,&nbsp;<strong>not including information collected from other sources such as e-mails etc.</strong>&nbsp;for marketing purposes. This consent is purely voluntary and you may at any time choose not to receive marketing materials from us by following the unsubscribe instructions included in each e-mail you may receive, by indicating so when we call you, or by contacting us directly. Further, if you want to remove your contact information from all our lists and newsletters, please click on the unsubscribe button on the emailers or send an email request to&nbsp.</p>
                        <p>Subject to explicit and prior consent from you, we may disclose certain information that is created by your use of our App to CRED’s subsidiaries, affiliate entities and partners that are not acting as our suppliers or business partners. For the sake of clarity, we do not sell or lease such information.</p>
                        <p>Some of our campaigns/programmes/related events may be co-branded, that is sponsored by both the third parties and us. If you sign up for such campaigns/programmes/related events, please note that your information may also be collected by and shared with those third parties. We urge you to familiarise yourself with their privacy policies to gain an understanding of the manner in which they will handle information about you.</p>
                        <p>CRED allows users to use their CRED account to log into or access other websites or applications using the CRED Access feature. Upon logging in to such third party websites or application using your CRED account, certain information (as set out on CRED Access log-in screen) shall be shared with the relevant third party website and application and will be subject to such third party’s terms of use and privacy policy.</p>
                        <p>We may display targeted or non-targetted third party online advertisements on the CRED website/app. We may also advertise our activities and organizational goals on other websites/apps. We may collaborate with other website/app operators as well as network advertisers to do so. We request you to read and understand such concerned third party privacy policies to understand their practices relating to advertising, including what type of information they may collect about your internet usage.&nbsp;<strong>No personally identifiable information is shared with any third party online advertiser or website or app as part of any such activity. CRED does not provide any information relating to your usage to such website operators or network advertisers.</strong></p>
                        <p>During your use of the App, you may come across links to third party websites/apps that are not affiliated with CRED. CRED is not responsible for the privacy practices or the content of those other websites, or for any acts/ omissions by such third parties in the course of your transaction with them.&nbsp;</p>
                        <h2><strong>3. Account/Card Deletion</strong></h2>
                        <p>We provide all our Users an option to request the deletion a specific account through the support section on the CRED App. Following such request, we delete all such information related to the specific account including but not limited to profile information, card data, transaction details, reward details, referrals details, statement details, google oauth sessions etc. that we are not required to retain.</p>
                        <p>In certain circumstances, we may be unable to delete your account, such as if there is any outstanding dispute, loan products availed through the CRED App or unresolved claims pending on your card/account. However, upon resolution of the issue preventing deletion, the information is immediately deleted and can’t be recovered thereafter.&nbsp;<strong>Note that we may retain certain information if necessary for our own legitimate business interests such as fraud prevention and enhancing users’ safety and security or to fulfil our legal and contractual obligations and compliance requirements. </strong></p>
                        
                        <h2><strong>4. Cookies</strong></h2>
                        <p>We use data collection devices such as “cookies”, etc. on certain parts of the App to help analyse the App Services, user interaction with the App, measure promotional effectiveness, and promote trust and safety. For the sake of clarity, “cookies” are small files placed on your device hard-drive/storage that assist us in providing the services offered through the App. Please be informed that we offer certain features via the App that are only available through the use of a “cookie”.</p>
                        <p>We also use cookies to allow you to enter a particular password less frequently during a session. Cookies also help us obtain information that assists us in curating the Services more targeted to your interests. You are always free to decline our cookies if your device permits, although in that case you may not be able to use certain features on the app and you may be required to provide a password more frequently during a session.</p>
                        <h2><strong>5. Changes to Privacy Policy</strong></h2>
                        <p>Dreamplug reserves the right to change this policy from time to time. Any changes shall be effective immediately upon the posting of the revised Privacy Policy. We encourage you to periodically review this page for latest information on our privacy practices.</p>
                        <h2><strong>6. Privacy Questions and Access</strong></h2>
                        <p>If you have questions, concerns, or suggestions regarding our Privacy Policy, we can be reached using the contact information on our “Contact Us” page or at&nbsp;. In certain cases, you may have the ability to view or edit your personal information online. In the event your information is not accessible online and you wish to obtain a copy of particular information you provided to us, or if you become aware the information is incorrect and you would like us to correct it, please contact us immediately.</p>
                        <p>Before we are able to provide you with any information or correct any inaccuracies, however, we may ask you to verify your identity and to provide other details to ascertain your identity and to help us to respond to your request. We will contact you within 30 days of your request.</p>
                        <h2><strong>7. Compliances</strong></h2>
                        <p>We are an ISO 27001:2013 certified company and have implemented required Information Systems Management System policies and procedures in order to maintain industry standard best practices and applicable controls.</p>
                        <p>We have successfully completed “Data Localization” requirements as per Reserve Bank of India (RBI) guidelines. This means all our customer data securely resides inside on one or more data centres located within India.</p>
                        <p>CRED use of information received from Google APIs will adhere to including the Limited Use requirements.</p>
                        <h2><strong>8. Grievance Redressal Officer</strong></h2>
                        <p>In the event that you have a grievance regarding our privacy policy or data usage practices, you may reach out to our Grievance Redressal Officer at the details below:</p>
                        
                            <p></p>
                        </div>
                    </div>
            </section>
        </div>
    )
}
